# Generated by Django 5.1.4 on 2026-05-27 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_account_email', models.EmailField(max_length=254)),
                ('_access_token', models.TextField(db_column='access_token')),
                ('_refresh_token', models.TextField(db_column='refresh_token')),
                ('token_expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_connections', to='accounts.workspace')),
            ],
            options={
                'db_table': 'google_ads_connections',
                'unique_together': {('workspace', 'google_account_email')},
            },
        ),
        migrations.CreateModel(
            name='HubSpotIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_id', models.CharField(max_length=20)),
                ('_access_token', models.TextField(db_column='hubspot_access_token')),
                ('_refresh_token', models.TextField(db_column='hubspot_refresh_token')),
                ('token_expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_integration', to='accounts.workspace')),
            ],
            options={
                'db_table': 'hubspot_integrations',
            },
        ),
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_workspace_name', models.CharField(max_length=255)),
                ('slack_workspace_id', models.CharField(max_length=50)),
                ('_access_token', models.TextField(db_column='slack_access_token')),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to='accounts.workspace')),
            ],
            options={
                'db_table': 'slack_integrations',
            },
        ),
        migrations.CreateModel(
            name='MonitoredAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_ads_customer_id', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('time_zone', models.CharField(default='UTC', max_length=50)),
                ('is_manager_account', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_accounts', to='integrations.googleadsconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_accounts', to='accounts.workspace')),
            ],
            options={
                'db_table': 'monitored_accounts',
                'unique_together': {('workspace', 'google_ads_customer_id')},
            },
        ),
    ]
