# Generated by Django 5.1.4 on 2026-05-27 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('health_score', models.IntegerField(blank=True, null=True)),
                ('pass_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('estimated_wasted_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_runs', to='integrations.monitoredaccount')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_key', models.CharField(db_index=True, max_length=100)),
                ('check_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warning', 'Warning'), ('critical', 'Critical'), ('error', 'Error')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('finding_summary', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('fix_instructions', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='audits.auditrun')),
            ],
            options={
                'db_table': 'audit_checks',
                'ordering': ['category', 'check_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='integrations.monitoredaccount')),
            ],
            options={
                'db_table': 'audit_schedules',
            },
        ),
        migrations.CreateModel(
            name='HealthScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='integrations.monitoredaccount')),
                ('audit_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_score_record', to='audits.auditrun')),
            ],
            options={
                'db_table': 'health_score_history',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
